services:
  jenkins: 
    build: ./dilopez_jenkins 
    image: jenkins/jenkins:lts-jdk11 
    networks:
    - devops_network
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes: 
      - jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock 
    deploy:
      resources:
        limits:
          memory: 1G
  nexus: 
    build: ./dilopez_nexus 
    image: sonatype/nexus3:latest
    networks:
    - devops_network
    ports: 
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-datai
  rundeck:
    image: rundeck/rundeck
    network:
    - devops_network
    ports: 
      - "4440:4440"
      - "4443:4443"
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  jenkins_home:
  nexus-data:
networks:
  devops_network:
    driver: bridge
