---
  - import_playbook: vim.yaml
  - import_playbook: ansible.yaml
  - import_playbook: toolchain.yaml
  - import_playbook: docker.yaml
  - import_playbook: rundeck.yaml
  - import_playbook: nagios.yaml
