---
  - name: "Install Rundeck"
    hosts: master
    become: true
    vars:
      domain: "{{ ansible_all_ipv4_addresses | select('match','^192.168*') | list | first}}"
      rundeck_url: "http://{{ domain }}:4440"
    environment:
      RD_URL: "{{ rundeck_url | string }}"
      RD_USER: admin
      RD_PASSWORD: admin
    tasks:
    - name: "Installing Java"
      apt:
        update_cache: true
        pkg:
        - openjdk-11-jre-headless
        state: latest
    - name: "Importing the repo signing key"
      apt_key:
        url: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
        state: present
    - name: "Adding repository"
      copy:
        src: ../../rundeck/rundeck.list
        dest: /etc/apt/sources.list.d/rundeck.list
    - name: "Installing Rundeck"
      apt:
        update_cache: true
        pkg:
        - rundeck
        - rundeck-cli
        state: latest
    - name: "Update Grails URL"
      template:
        src: /opt/dilopez-devops/toolchain/rundeck/rundeck-config.properties 
        dest: /etc/rundeck/rundeck-config.properties
        owner: rundeck
        group: rundeck
        mode: 0640
    - name: "Copy hosts file"
      copy:
        src: /opt/dilopez-devops/toolchain/rundeck/hosts
        dest: /etc/ansible/hosts
    - name: "Enable Service"
      systemd:
        service: rundeckd
        enabled: true
        state: restarted
    - name: "Add Key-Pair"
      openssh_keypair:
        path: /var/lib/rundeck/.ssh/id_rsa
        owner: rundeck
        group: rundeck
    - name: "Wait for Port 4440"
      wait_for:
        port: 4440
    - name: "Add Ansible Playbooks Project"
      command: rd projects create -p ansible-playbooks -f /opt/dilopez-devops/toolchain/rundeck/projects/ansible-playbooks/project.properties
      ignore_errors: yes
    - name: "Add Master Job"
      command: rd jobs load -p ansible-playbooks -f /opt/dilopez-devops/toolchain/rundeck/projects/ansible-playbooks/master-playbook.xml
      ignore_errors: yes
