---
  #https://puppet.com/docs/puppet/7/server/install_from_packages.html
  - name: "Configure Puppet"                                             
    hosts: 192.168.50.11
    become: true
    tasks:                                                                      
    - name: "Install dependencies"                                              
      apt:                                                                      
        update_cache: true 
        pkg:                                                                    
        - ruby
        - build-essential                                                       
        - openjdk-11-jdk                                                        
        - vim                                                                   
        - git                                                                   
        state: latest                                                           
    - name: "Download Puppet 7"                                                 
      get_url:                                                                  
        url: https://apt.puppet.com/puppet7-release-focal.deb                   
        dest: /root/puppet7-release-focal.deb                                   
    - name: "Enable Puppet APT"                                                 
      apt:                                                                      
        deb: /root/puppet7-release-focal.deb                                    
        state: present                                                          
  - name: "Configure Puppet Agent"
    hosts: 192.168.50.11
    become: true
    tasks:
    - name: "Add environment variables"
      lineinfile:
        path: /root/.bashrc
        line: export PATH={$PATH}:/opt/puppetlabs/bin
    - name: "Copy Master FQDN"
      copy:
        src: /home/vagrant/fqdn
        dest: /home/vagrant/fqdn
    - name: "Create FQDN Variable"
      command: cat /home/vagrant/fqdn
      register: fqdn
    - name: "Install Puppet Agent"
      apt:
        update_cache: true 
        pkg:
          - puppet-agent
        state: present
    - name: "Copy puppet.conf template"
      template:
        src: /home/vagrant/toolkit/puppet/puppetagent.conf
        dest: /etc/puppetlabs/puppet/puppet.conf
    - name: "Ensure Puppet Agent is running"
      command: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true
    - name: "Register Facter Domain"
      command: /opt/puppetlabs/bin/facter domain
      register: domain
    - name: "Add Puppet Server Line on /etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: 192.168.50.10 dilopezmaster.{{domain.stdout}} dilopezmaster.{{domain.stdout}}
      when: domain.stdout != ""
    - name: "Add Puppet Server Line on /etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: 192.168.50.10 dilopezmaster dilopezmaster
      when: domain.stdout == ""
    - name: "Add Puppet Agent Line on /etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: 192.168.50.11 dilopezagent.{{domain.stdout}} dilopezagent.{{domain.stdout}}
      when: domain.stdout != ""
    - name: "Add Puppet Agent Line on /etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: 192.168.50.11 dilopezagent dilopezagent
      when: domain.stdout == ""
    - name: "Puppet Agent Handshake"
      command: /opt/puppetlabs/bin/puppet ssl bootstrap
      async: 45
      poll: 0
  - name: "Puppet Server Handshake"
    hosts: localhost
    connection: local
    become: true
    tasks:
      - name: "Puppet Server Handshake"
        command: /opt/puppetlabs/bin/puppetserver ca sign --all
