---
  - name: "Configure Puppet #1"
    hosts: 192.168.50.11
    become: true
    tasks:
    - name: "Agent SSL Bootstrap"
      shell: puppet ssl bootstrap
  - name: "Configure Puppet #2"
    hosts: 192.168.50.10
    become: true
    tasks:
    - name: "Sign Certificates"
      shell: puppetserver ca sign --all
  - name: "Configure Puppet #3"
    hosts: 192.168.50.11
    become: true
    tasks:
    - name: "Agent SSL Bootstrap"
      shell: puppet ssl bootstrap
